# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued term

# 在斐波那契数列中，找出4 000 000以下的项中值为偶数的项之和

def fib maxnum, initial = [1,2]
  i, j = initial
  arr = []

  while i <= maxnum do
    arr << i
    i,j = j, i+j
  end

  puts arr
  sum = arr.select{ |n| n.even? }.inject(:+)
  puts "sum = #{sum}"
end

fib(4000000)
